#!/usr/bin/env python3
"""
inspect_quota.py

Safe read-only parser and normalizer for AGM (Antigravity Manager) quota output.
Converts table output into a structured, typed AccountQuota schema
with strict RefreshEvidence provenance validation and schema header checking.

Core Principles:
1. PARSED_AT is NEVER treated as proof of quota freshness.
2. Freshness requires explicit, validated RefreshEvidence records generated by refresh executor.
3. Arbitrary caller timestamps without validated RefreshEvidence are rejected as STALE_CACHED.
4. Schema header format changes fail closed as FORMAT_UNSUPPORTED unless research-lenient-parser is explicitly enabled.
5. Info mode and List mode both accept typed RefreshEvidence.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from enum import Enum
from typing import Dict, List, Optional, Tuple, Union

# Add current dir to path to import refresh_quota_safe
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from refresh_quota_safe import RefreshEvidence, RefreshResult


class FreshnessState(str, Enum):
    PROVEN_FRESH = "PROVEN_FRESH"
    STALE_CACHED = "STALE_CACHED"
    REFRESH_FAILED = "REFRESH_FAILED"
    UNKNOWN_UNFETCHED = "UNKNOWN_UNFETCHED"


class FormatSupportState(str, Enum):
    FORMAT_SUPPORTED = "FORMAT_SUPPORTED"
    FORMAT_UNSUPPORTED = "FORMAT_UNSUPPORTED"


@dataclass
class ModelQuotaDetail:
    model_name: str
    provider: str
    remaining_pct: Optional[int]  # None if unknown / unparseable, 0-100 if integer
    reset_time: Optional[str]
    freshness_state: FreshnessState


@dataclass
class AccountQuotaSummary:
    safe_account_ref: str
    status_tags: List[str]
    is_active_cli: bool
    is_active_ide: bool
    is_token_expired: bool
    gemini_pro_pct: Optional[int]
    gemini_flash_pct: Optional[int]
    claude_pct: Optional[int]
    models: Dict[str, ModelQuotaDetail]
    parsed_at_epoch: float
    refresh_confirmed_at_epoch: Optional[float]
    quota_reset_time: Optional[str]
    freshness_state: FreshnessState
    format_support: FormatSupportState
    source: str  # "AGM_CLI_LIST", "AGM_CLI_INFO", "DB_DIRECT", "MOCK_FIXTURE"
    parse_warnings: List[str]
    eligible: bool


def parse_percentage_field(val: str) -> Optional[int]:
    """Parse percentage string safely. Returns None on '-', 'NaN', or invalid."""
    if not val:
        return None
    val = val.strip()
    if val in ("-", "unknown", "N/A", "null", "none", "???"):
        return None
    m = re.match(r"^(\d{1,3})%$", val)
    if m:
        try:
            num = int(m.group(1))
            if 0 <= num <= 100:
                return num
        except ValueError:
            return None
    return None


def validate_refresh_evidence(
    evidence: Optional[Union[RefreshEvidence, dict]],
    canonical_account: str,
    now_epoch: float,
    max_freshness_age_sec: int = 300,
    expected_session_id: Optional[str] = None
) -> Tuple[FreshnessState, Optional[float], List[str]]:
    """
    Validates a RefreshEvidence object for a given canonical account.
    Returns (FreshnessState, refresh_confirmed_at_epoch, warnings).
    """
    warnings: List[str] = []
    if evidence is None:
        return FreshnessState.STALE_CACHED, None, ["No refresh evidence provided; treating cached quota as STALE_CACHED"]

    # Convert dict to RefreshEvidence if needed
    if isinstance(evidence, dict):
        try:
            res_val = evidence.get("result")
            if isinstance(res_val, str):
                res_enum = RefreshResult(res_val)
            else:
                res_enum = res_val
            evidence = RefreshEvidence(
                canonical_account=evidence.get("canonical_account", ""),
                agm_executable=evidence.get("agm_executable", ""),
                agm_version_or_revision=evidence.get("agm_version_or_revision", ""),
                command=evidence.get("command", ""),
                started_at_epoch=float(evidence.get("started_at_epoch", 0.0)),
                completed_at_epoch=float(evidence.get("completed_at_epoch", 0.0)),
                exit_code=int(evidence.get("exit_code", 1)),
                result=res_enum,
                supervisor_session_id=evidence.get("supervisor_session_id", ""),
                error_summary=evidence.get("error_summary")
            )
        except Exception as e:
            return FreshnessState.STALE_CACHED, None, [f"Malformed RefreshEvidence record: {e}"]

    # Check account matching
    if evidence.canonical_account.lower() != canonical_account.lower():
        return FreshnessState.STALE_CACHED, None, [
            f"Refresh evidence account mismatch (expected '{canonical_account}', got '{evidence.canonical_account}')"
        ]

    # Check supervisor session matching if requested
    if expected_session_id and evidence.supervisor_session_id != expected_session_id:
        return FreshnessState.STALE_CACHED, None, [
            f"Refresh evidence session mismatch (expected session '{expected_session_id}', got '{evidence.supervisor_session_id}')"
        ]

    # Check result status
    if evidence.result != RefreshResult.REFRESH_SUCCEEDED:
        return FreshnessState.REFRESH_FAILED, None, [
            f"Quota refresh failed with status {evidence.result.value}: {evidence.error_summary or 'non-zero exit'}"
        ]

    # Check age
    age = now_epoch - evidence.completed_at_epoch
    if age < 0:
        warnings.append(f"Refresh completed_at is in the future by {-age:.1f}s")
    if age > max_freshness_age_sec:
        return FreshnessState.STALE_CACHED, evidence.completed_at_epoch, [
            f"Refresh evidence expired ({age:.1f}s > max {max_freshness_age_sec}s)"
        ]

    return FreshnessState.PROVEN_FRESH, evidence.completed_at_epoch, warnings


def parse_agm_list(
    text: str,
    refresh_evidence_map: Optional[Dict[str, Union[RefreshEvidence, dict]]] = None,
    raw_unvalidated_timestamps: Optional[Dict[str, float]] = None,
    max_freshness_age_sec: int = 300,
    source_label: str = "AGM_CLI_LIST",
    expected_session_id: Optional[str] = None,
    lenient_parser: bool = False,
    now_epoch: Optional[float] = None
) -> List[AccountQuotaSummary]:
    """
    Parses the standard output of `agm list`.
    Enforces strict schema header validation and RefreshEvidence provenance.
    """
    now = now_epoch if now_epoch is not None else time.time()
    ev_map = refresh_evidence_map or {}

    lines = text.strip().splitlines()
    if not lines:
        return []

    if any("No accounts yet" in line for line in lines):
        return []

    results: List[AccountQuotaSummary] = []
    header_found = False
    col_bounds = None
    format_state = FormatSupportState.FORMAT_UNSUPPORTED

    # Detect header and validate supported schema
    for line in lines:
        if "EMAIL" in line and "STATUS" in line and "GEM-PRO" in line and "GEM-FLASH" in line and "CLAUDE" in line:
            header_found = True
            email_idx = line.find("EMAIL")
            status_idx = line.find("STATUS")
            gp_idx = line.find("GEM-PRO")
            gf_idx = line.find("GEM-FLASH")
            cl_idx = line.find("CLAUDE")
            if email_idx < status_idx < gp_idx < gf_idx < cl_idx:
                col_bounds = (email_idx, status_idx, gp_idx, gf_idx, cl_idx)
                format_state = FormatSupportState.FORMAT_SUPPORTED
            break

    if (not header_found or format_state == FormatSupportState.FORMAT_UNSUPPORTED) and not lenient_parser:
        # Schema unsupported -> Fail closed!
        return [
            AccountQuotaSummary(
                safe_account_ref="UNKNOWN_UNSUPPORTED_SCHEMA",
                status_tags=[],
                is_active_cli=False,
                is_active_ide=False,
                is_token_expired=False,
                gemini_pro_pct=None,
                gemini_flash_pct=None,
                claude_pct=None,
                models={},
                parsed_at_epoch=now,
                refresh_confirmed_at_epoch=None,
                quota_reset_time=None,
                freshness_state=FreshnessState.UNKNOWN_UNFETCHED,
                format_support=FormatSupportState.FORMAT_UNSUPPORTED,
                source=source_label,
                parse_warnings=["AGM output header does not match expected supported schema. Fail closed."],
                eligible=False
            )
        ]

    for line in lines:
        line_clean = line.strip()
        if not line_clean:
            continue
        if "EMAIL" in line and "STATUS" in line:
            continue
        if line_clean.startswith("---") or line_clean.startswith("==="):
            continue

        warnings: List[str] = []
        if col_bounds:
            e_idx, s_idx, gp_idx, gf_idx, cl_idx = col_bounds
            email_part = line[e_idx:s_idx].strip() if len(line) > s_idx else line.strip()
            status_part = line[s_idx:gp_idx].strip() if len(line) > gp_idx else ""
            gp_part = line[gp_idx:gf_idx].strip() if len(line) > gf_idx else ""
            gf_part = line[gf_idx:cl_idx].strip() if len(line) > cl_idx else ""
            cl_part = line[cl_idx:].strip() if len(line) > cl_idx else ""
        elif lenient_parser:
            tokens = line_clean.split()
            if len(tokens) < 1 or "@" not in tokens[0]:
                continue
            email_part = tokens[0]
            status_part = tokens[1] if len(tokens) > 1 else ""
            gp_part = tokens[2] if len(tokens) > 2 else ""
            gf_part = tokens[3] if len(tokens) > 3 else ""
            cl_part = tokens[4] if len(tokens) > 4 else ""
            warnings.append("Parsed using research-lenient fallback tokenization")
        else:
            continue

        if "@" not in email_part:
            continue

        tags = [t.strip() for t in status_part.split(",") if t.strip()]
        is_expired = "token-exp" in tags

        gp_val = parse_percentage_field(gp_part)
        gf_val = parse_percentage_field(gf_part)
        cl_val = parse_percentage_field(cl_part)

        if gp_part and gp_part != "-" and gp_val is None:
            warnings.append(f"Malformed GEM-PRO quota string: '{gp_part}'")
        if gf_part and gf_part != "-" and gf_val is None:
            warnings.append(f"Malformed GEM-FLASH quota string: '{gf_part}'")
        if cl_part and cl_part != "-" and cl_val is None:
            warnings.append(f"Malformed CLAUDE quota string: '{cl_part}'")

        # Validate Refresh Evidence
        if raw_unvalidated_timestamps and email_part in raw_unvalidated_timestamps:
            warnings.append("Raw unvalidated timestamp provided without RefreshEvidence; rejected as STALE_CACHED")
            freshness = FreshnessState.STALE_CACHED
            ref_confirmed_at = None
        elif email_part in ev_map:
            freshness, ref_confirmed_at, ev_warn = validate_refresh_evidence(
                ev_map[email_part],
                canonical_account=email_part,
                now_epoch=now,
                max_freshness_age_sec=max_freshness_age_sec,
                expected_session_id=expected_session_id
            )
            warnings.extend(ev_warn)
        elif all(v is None for v in [gp_val, gf_val, cl_val]):
            freshness = FreshnessState.UNKNOWN_UNFETCHED
            ref_confirmed_at = None
        else:
            freshness = FreshnessState.STALE_CACHED
            ref_confirmed_at = None

        all_zero = (
            any(v == 0 for v in [gp_val, gf_val, cl_val] if v is not None)
            and all(v == 0 for v in [gp_val, gf_val, cl_val] if v is not None)
        )
        eligible = (
            (not is_expired)
            and (not all_zero)
            and (freshness == FreshnessState.PROVEN_FRESH)
            and (format_state == FormatSupportState.FORMAT_SUPPORTED)
        )

        results.append(AccountQuotaSummary(
            safe_account_ref=email_part,
            status_tags=tags,
            is_active_cli="cli" in tags,
            is_active_ide="ide" in tags,
            is_token_expired=is_expired,
            gemini_pro_pct=gp_val,
            gemini_flash_pct=gf_val,
            claude_pct=cl_val,
            models={},
            parsed_at_epoch=now,
            refresh_confirmed_at_epoch=ref_confirmed_at,
            quota_reset_time=None,
            freshness_state=freshness,
            format_support=format_state,
            source=source_label,
            parse_warnings=warnings,
            eligible=eligible
        ))

    return results


def parse_agm_info(
    text: str,
    refresh_evidence: Optional[Union[RefreshEvidence, dict]] = None,
    raw_unvalidated_timestamp: Optional[float] = None,
    max_freshness_age_sec: int = 300,
    source_label: str = "AGM_CLI_INFO",
    expected_session_id: Optional[str] = None,
    now_epoch: Optional[float] = None
) -> Optional[AccountQuotaSummary]:
    """
    Parses output of `agm info <email>`.
    Accepts and validates RefreshEvidence provenance.
    """
    now = now_epoch if now_epoch is not None else time.time()
    lines = text.strip().splitlines()
    if not lines:
        return None

    email = ""
    is_expired = False
    models: Dict[str, ModelQuotaDetail] = {}
    warnings: List[str] = []
    in_table = False
    earliest_reset = None

    for line in lines:
        line_clean = line.strip()
        if line_clean.startswith("Account:"):
            email = line_clean.split("Account:", 1)[1].strip()
        elif line_clean.startswith("Token expiry:"):
            if "(expired)" in line_clean:
                is_expired = True
        elif "No quota data" in line_clean:
            warnings.append("No quota data recorded in store")
        elif "PROVIDER" in line and "MODEL" in line and "SCORE" in line:
            in_table = True
            continue
        elif line_clean.startswith("---") or line_clean.startswith("==="):
            continue
        elif in_table and line_clean:
            tokens = line_clean.split()
            if len(tokens) >= 3:
                provider = tokens[0]
                model = tokens[1]
                score_str = tokens[2]
                reset_str = tokens[3] if len(tokens) > 3 else None
                if reset_str and not earliest_reset:
                    earliest_reset = reset_str
                pct = parse_percentage_field(score_str)
                if pct is None and score_str != "-":
                    warnings.append(f"Malformed score for model {model}: '{score_str}'")

                models[model] = ModelQuotaDetail(
                    model_name=model,
                    provider=provider,
                    remaining_pct=pct,
                    reset_time=reset_str,
                    freshness_state=FreshnessState.STALE_CACHED
                )

    if not email:
        return None

    # Validate provenance for info mode
    if raw_unvalidated_timestamp is not None:
        warnings.append("Raw unvalidated timestamp provided without RefreshEvidence; rejected as STALE_CACHED")
        freshness = FreshnessState.STALE_CACHED
        ref_confirmed_at = None
    elif refresh_evidence is not None:
        freshness, ref_confirmed_at, ev_warn = validate_refresh_evidence(
            refresh_evidence,
            canonical_account=email,
            now_epoch=now,
            max_freshness_age_sec=max_freshness_age_sec,
            expected_session_id=expected_session_id
        )
        warnings.extend(ev_warn)
    elif len(models) == 0:
        freshness = FreshnessState.UNKNOWN_UNFETCHED
        ref_confirmed_at = None
    else:
        freshness = FreshnessState.STALE_CACHED
        ref_confirmed_at = None

    # Update models freshness state
    for m in models.values():
        m.freshness_state = freshness

    gp_pcts = [m.remaining_pct for name, m in models.items() if "gemini" in name.lower() and "pro" in name.lower() and m.remaining_pct is not None]
    gf_pcts = [m.remaining_pct for name, m in models.items() if "gemini" in name.lower() and "flash" in name.lower() and m.remaining_pct is not None]
    cl_pcts = [m.remaining_pct for name, m in models.items() if "claude" in name.lower() and m.remaining_pct is not None]

    gp_val = min(gp_pcts) if gp_pcts else None
    gf_val = min(gf_pcts) if gf_pcts else None
    cl_val = min(cl_pcts) if cl_pcts else None

    eligible = (
        (not is_expired)
        and (freshness == FreshnessState.PROVEN_FRESH)
        and any(m.remaining_pct is not None and m.remaining_pct > 0 for m in models.values())
    )

    return AccountQuotaSummary(
        safe_account_ref=email,
        status_tags=["token-exp"] if is_expired else [],
        is_active_cli=False,
        is_active_ide=False,
        is_token_expired=is_expired,
        gemini_pro_pct=gp_val,
        gemini_flash_pct=gf_val,
        claude_pct=cl_val,
        models=models,
        parsed_at_epoch=now,
        refresh_confirmed_at_epoch=ref_confirmed_at,
        quota_reset_time=earliest_reset,
        freshness_state=freshness,
        format_support=FormatSupportState.FORMAT_SUPPORTED,
        source=source_label,
        parse_warnings=warnings,
        eligible=eligible
    )


def main():
    parser = argparse.ArgumentParser(description="Inspect and normalize AGM quota output with typed RefreshEvidence provenance.")
    parser.add_argument("--file", "-f", help="Read raw AGM output from file")
    parser.add_argument("--mode", "-m", choices=["list", "info", "auto"], default="auto", help="Parsing mode")
    parser.add_argument("--provenance-json", help="Optional JSON dict of RefreshEvidence mapping email -> record")
    parser.add_argument("--research-lenient-parser", action="store_true", help="Enable research fallback tokenization")
    args = parser.parse_args()

    ev_map = {}
    if args.provenance_json:
        try:
            ev_map = json.loads(args.provenance_json)
        except Exception as e:
            print(f"Error parsing provenance JSON: {e}", file=sys.stderr)
            sys.exit(1)

    if args.file:
        with open(args.file, "r", encoding="utf-8") as f:
            content = f.read()
    else:
        if not sys.stdin.isatty():
            content = sys.stdin.read()
        else:
            try:
                res = subprocess.run(["agm", "list"], capture_output=True, text=True, check=True)
                content = res.stdout
            except Exception as e:
                print(f"Error executing agm list: {e}", file=sys.stderr)
                sys.exit(1)

    mode = args.mode
    if mode == "auto":
        if "PROVIDER" in content and "MODEL" in content and "Account:" in content:
            mode = "info"
        else:
            mode = "list"

    if mode == "info":
        # Pass first matching evidence in info mode if available
        first_ev = next(iter(ev_map.values())) if ev_map else None
        res = parse_agm_info(content, refresh_evidence=first_ev)
        data = asdict(res) if res else None
    else:
        res_list = parse_agm_list(
            content,
            refresh_evidence_map=ev_map,
            lenient_parser=args.research_lenient_parser
        )
        data = [asdict(r) for r in res_list]

    print(json.dumps(data, indent=2))


if __name__ == "__main__":
    main()
